services:
  app:
    build:
      context: .
      target: development
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8000:3000"
    volumes:
      - ./src:/app/src  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules
    tty: true
    networks:
      app-network:

  database:
    build:
      context: https://github.com/trendy-sand-dance/databaseContainer.git
      dockerfile: Dockerfile
    image: better-sqlite3
    container_name: database_container-db
    volumes:
      - database_data:/app/src/database
    networks:
     - app-network

  #user-service:
  #  container_name: user_container-db
  #  build:
  #    context: https://github.com/trendy-sand-dance/userManagementContainer.git
  #    dockerfile: Dockerfile
  #  volumes:
  #    - database_data:/app/src/database
  #  depends_on:
  #    - database
  #  networks:
  #    - app-network

volumes:
  database_data:

networks:
  app-network: